### ISSUE TITLE
Commented @properties included in generated description

### ISSUE THREAD

**Issue by sneakyness** [adamontherun/xCodeGenerateDescriptionPlugin#1]
##### Repro steps:
1. Comment out a `@property`
2. Highlight the line of the commented out `@property`
3. Generate Description
##### Result:

It generates a description including the commented out description 
##### Expected Result:

It ignores commented out properties when generating the description.

PS Thanks for making this, it's saved me a ton of time :+1:

**Comment by adamontherun** [comment]
functionality added
