### ISSUE TITLE
The keyboard shortcut doesn't seem to work

### ISSUE THREAD

**Issue by lenkaiser** [adamontherun/xCodeGenerateDescriptionPlugin#11]
The keyboard shortcut is pre-defined on ⌃ + ⌘ + M. I'm not sure if it's possible to change this shortcut and if so where could I? But this shortcut is by default set to 'Issues -> Show All Issues' in Xcode so this interferes with the plugin shortcut.

P.S. Even then it doesn't seem to work, can you verify this?

**Comment by adamontherun** [comment]
Hi, I noticed this as well. Made a change to the hot key to make it unique, and it should work fine now. thanks for the heads up.
