### ISSUE TITLE
Feature Request: Any way to automate printing descriptions?

### ISSUE THREAD

**Issue by jstart** [adamontherun/xCodeGenerateDescriptionPlugin#17]
I know this is a little off topic, but is there any way of achieving this feature without introducing new code to implement the description method?  Is there a way to make a like plugin for the debugger that would look at the class and generate the description when a print/po function is called?

**Comment by adamontherun** [comment]
something that I'll keep in mind, but won't be implementing in the near future. I'd find this useful as well.
