### ISSUE TITLE
Doesn't work with Xcode 7?

### ISSUE THREAD

**Issue by Tiger-Coding** [adamontherun/xCodeGenerateDescriptionPlugin#19]
Re-installed via instructions in the readme (running the project) and still failed to respond to triple forward slashes: ///

**Comment by adamontherun** [comment]
thanks for heads up @Tiger-Coding I just updated the plugin and it should work with Xcode 7.0 and the 7.1 beta now.

**Comment by zgp123** [comment]
not found  Make Description
