### ISSUE TITLE
Cannot generate additional descriptions if file contains multiple classes

### ISSUE THREAD

**Issue by sneakyness** [adamontherun/xCodeGenerateDescriptionPlugin#2]
##### Repro steps:
1. Make/Find a file with multiple classes
2. Highlight the first object's properties and generate a description for the first object, admire the usefulness of this wonderful tool
3. Highlight the second object's properties and generate a description for the second object

_Bonus Bug: If you have commented out a previous description, the same issue happens._
##### Result:

A dialog appears informing you that you must delete the existing description before you generate a new one.
##### Expected Result:

It generates the description and places it within the correct class.

**Comment by adamontherun** [comment]
@sneakyness I think this is a good idea, but would require that the logic for matching the properties to the description method would have to be completely re-written. If anyone wants to try, I'd be happy to accept the pull request.
