### ISSUE TITLE
XCode 7.2 menu item not visible fix

### ISSUE THREAD

**Issue by Drenov** [adamontherun/xCodeGenerateDescriptionPlugin#24]
If this plugin just installed via Alcatraz, it is not visible in menu.
After adding the key to DVTPlugInCompatibilityUUIDs in plist all works normally.
Keys -
<string>CC0D0F4F-05B3-431A-8F33-F84AFCB2C651</string>  
<string>7265231C-39B4-402C-89E1-16167C4CC990</string>  
<string>9AFF134A-08DC-4096-8CEE-62A4BB123046</string>  
 <string>F41BD31E-2683-44B8-AE7F-5F09E919790E</string> 

Plist at /Library/Application Support/Developer/Shared/Xcode/Plug-ins/AutoGenerateDescriptionPluginProd.xcplugin/Contents

**Comment by adamontherun** [comment]
just fixed. thank you.
