### ISSUE TITLE
Certain comments cause crashes

### ISSUE THREAD

**Issue by sneakyness** [adamontherun/xCodeGenerateDescriptionPlugin#4]
`@property (nonatomic, weak) NSObject *someObject; // informative comment here referencing (SomeThingElseOrMaybeTheSameThing *bacon)`

Will crash Xcode if it is included in the highlight upon generation

**Comment by beat843796** [comment]
header doc comments are causing xcode to beachball

**Comment by adamontherun** [comment]
thanks for reporting this. issue is resolved with latest build.
