### ISSUE TITLE
two description in one .m

### ISSUE THREAD

**Issue by ajjnix** [adamontherun/xCodeGenerateDescriptionPlugin#9]
I has two interface in one .h
and two implement in one .m

NNCatalog and NNCatalogExtraModel

I has generate two description but don't work.

**Comment by adamontherun** [comment]
Hi @ajjnix, this would be a great feature, but would require a large re-write of the plugin and I don't have time at the moment. Always open to pull request though.
thanks
adam

**Comment by ajjnix** [comment]
Ok, I try to correct in free time (sorry of my English)
